name: Top GitHub Users
on:
  schedule:
    - cron: '* */20 * * *'
  workflow_dispatch:
jobs:
  release:
    name: GitHub Active Users
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.CUSTOM_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: MuhammadSaadSiddique/top-github-users-action@master
        env:
          CUSTOM_TOKEN: ${{ secrets.CUSTOM_TOKEN }}
